### PR TITLE
:eyes: change docker volume to new output folder

### PR DESCRIPTION
**Pull request by markysoft**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of pomi-data-etl succeeded (http://pomi-data-etl-pr-21.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of pomi-data-etl succeeded (http://pomi-data-etl-pr-21.dev.beta.nhschoices.net)

**Review by st3v3nhunt — CHANGES_REQUESTED** [review]
~I'm getting `404`s on the PR env http://pomi-data-etl-pr-21.dev.beta.nhschoices.net/~
The `404`s are because is hasn't run yet...
What should this change be doing?

**Review by st3v3nhunt — APPROVED** [review]

**Review by st3v3nhunt — APPROVED** [review]
Assuming this change is about getting the links on the web page working. This has worked.

**Comment by markysoft** [comment]
The output folder was moved recently to avoid problems caused with symlinks when developing locally. The docker volume had not be changes to point to the new location.
This meant that the output json files would be lost on a new deployment as they were not on a named volume.
This PR changed the docker volume to the correct location (site/json) so the previously created JSON files are not lost when the ETL is redeployed or updated

**Pull request merged**
