### PR TITLE
Use Vault in CI scripts

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of pomi-data-etl succeeded (http://pomi-data-etl-pr-23.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of pomi-data-etl succeeded (http://pomi-data-etl-pr-23.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of pomi-data-etl succeeded (http://pomi-data-etl-pr-23.dev.beta.nhschoices.net)

**Review by st3v3nhunt — APPROVED** [review]
Env vars in Travis removed to bare minimum. Build successfully run subsequently.
LGTM

**Pull request merged**
